name: liquid_pull_to_refresh_pro
description: A beautiful and custom refresh indicator with some cool animations and transitions for flutter.
version: 3.0.1
homepage: https://github.com/alaalfam/Liquid-Pull-To-Refresh_Pro/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: